### ISSUE TITLE
IDEA 15 Preview

### ISSUE THREAD

**Issue by sammy-tam** [nicity/CppTools#19]
Can it be bumped so that we can try IDEA 15 Preview without breaking the project structure?

**Comment by schmunk42** [comment]
:+1:

**Comment by Opa-** [comment]
Would be great ! :+1:

**Comment by achedeuzot** [comment]
Yeah ! :+1:

**Comment by mirelon** [comment]
+1

**Comment by yaleh** [comment]
+1

WebStorm 11

**Comment by longrenle** [comment]
+1

**Comment by lylemoffitt** [comment]
+1

**Comment by toothrot** [comment]
@lylemoffitt so glad I came here from the notification of your insightful +1. Would have missed it if it weren't for github's amazing notification system.

**Comment by basicdays** [comment]
So looks like IntelliJ Idea now has another new major version. Also looks like they're now just version by the year, as version 2016 was just released. Not sure if the issue name needs to get updated to reflect that.

**Comment by alexisvincent** [comment]
What's the status on this?

**Comment by tux-mind** [comment]
Hi guys, instead of waiting for someone to resume the development of this plugin I made it by myself.

I worked around the deprecated calls by rewriting those snippet of codes that were using them.
I just make it build against my IntelliJIDEA Ultimate 2016.2 ( IU-145 , it ahould be IU-162 but this is the version that I have currently installed.. weired ... )

enjoy: https://github.com/tux-mind/CppTools/releases/tag/v145-atomic.bomb

:blush:

**Comment by alexisvincent** [comment]
@tux-mind Is there a practical way to get this working?

**Comment by alexisvincent** [comment]
@nicity What is your plan for this project?

**Comment by tux-mind** [comment]
@alexisvincent I'm working on it right now, it looks like that the generated zip it's a zipball of the sources instead of the compiled stuff.

My plans are to get this working because I don't want another IDE ( CLion ) when I already have a full licensed IU ( thanks to my university ) installed.
I need this plugin to work on a project of one of my courses.

**Comment by alexisvincent** [comment]
@tux-mind Same here, really dislike having to maintain a separate config for CLion. Really appreciate the time you're taking to work on this. The intellij community is going to love you xD

**Comment by tux-mind** [comment]
Thank you @alexisvincent :blush: 

I just make it works!

The way this plugin works it's a bit weired, you have to use it like a tool rather than a Language....

Anyway i didn't make another version singe the code is unchanged, I just updated the zip with missing stuff from previous releases and now it works like a charm :stuck_out_tongue_winking_eye: 

https://github.com/tux-mind/CppTools/releases/tag/v145-atomic.bomb

**Comment by alexisvincent** [comment]
@tux-mind This is awesome man. Would be really cool if you put it on the repo's. How exactly do i use it though, it fails on my side

**Comment by alexisvincent** [comment]
Oh, hold on it seems to be working. Will verify in a moment

**Comment by alexisvincent** [comment]
Whoop whoop 👍 Still having issues getting GOTO's working and stuff but Ill report back

**Comment by alexisvincent** [comment]
@tux-mind Does this properly work for you? I don't get any intelligent IDE support
